name = "swammarn"
main = "worker.ts"
compatibility_date = "2026-08-20"
compatibility_flags = ["nodejs_compat", "enable_nodejs_http_server_modules"]

[assets]
directory = "./dist/public"
binding = "ASSETS"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "9a951eeecff64bba8a98ab7029d4d876"

[vars]
NODE_ENV = "production"
