import { COOKIE_NAME } from "../shared/const.js";
import { getSessionCookieOptions } from "./_core/cookies.js";
import { systemRouter } from "./_core/systemRouter.js";
import { adminProcedure, protectedProcedure, publicProcedure, router } from "./_core/trpc.js";
import { and, asc, desc, eq, gte, lte, sql } from "drizzle-orm";
import { approvals, dailyStock, items, purchases, saleShopLines, sales, shops, getDb, listDailyStock, listItems, listPendingApprovals, listPurchases, listSales, listShops, writeAudit } from "./db.js";
import { orders, recipes, recipeLines, stockAdjustments, importBatches } from "../drizzle/schema.js";
import { z } from "zod";
import { calculateClosing, calculateUsed, deriveSequentialStockRows, migrateBackupSnapshot, normalizeDateRange, normalizePurchase, resolveIssuedQuantity, resolveOpeningQuantity, sumShopQuantities, validateBackupSnapshot, validateImportRows, weightedAverageCost } from "../shared/calculations.js";

const dateRange = z.object({ from: z.string(), to: z.string() }).transform(v => normalizeDateRange(v.from, v.to));
const numeric = z.coerce.number().finite();

export const appRouter = router({
  system: systemRouter,
  auth: router({
    me: publicProcedure.query(opts => opts.ctx.user),
    logout: publicProcedure.mutation(({ ctx }) => { const options = getSessionCookieOptions(ctx.req); const response = ctx.res as unknown as { clearCookie?: (name: string, options: Record<string, unknown>) => void }; response.clearCookie?.(COOKIE_NAME, { ...options, maxAge: -1 }); return { success: true } as const; }),
  }),
  imports: router({
    applyProduction: adminProcedure.input(z.object({ filename: z.string().min(1), rows: z.array(z.object({ Date: z.string(), Department: z.enum(["production", "packaging"]), Item: z.string().min(1), Unit: z.string().min(1), Opening: numeric, In: numeric, Issued: numeric, Return: numeric, Damage: numeric, Note: z.string().optional() })).min(1) })).mutation(async ({ input, ctx }) => {
      const db = await getDb(); if (!db) throw new Error("Database unavailable");
      const itemRows = await db.select().from(items); const existing = await db.select().from(dailyStock).where(and(gte(dailyStock.stockDate, input.rows[0].Date), lte(dailyStock.stockDate, input.rows[input.rows.length - 1].Date)));
      const approvedKeys = new Set(existing.map(row => `${row.stockDate}|${row.department}|${itemRows.find(item => item.id === row.itemId)?.name ?? row.itemId}`));
      const validation = validateImportRows(input.rows, approvedKeys); if (!validation.valid) throw new Error(validation.errors.join(" "));
      const resolved = input.rows.map(row => { const item = itemRows.find(candidate => candidate.name === row.Item); if (!item) throw new Error(`Unknown item: ${row.Item}`); return { row, item }; });
      const apply = async (tx: any) => { const batch = await tx.insert(importBatches).values({ filename: input.filename, schemaVersion: "1", rowCount: resolved.length, status: "applied", createdBy: ctx.user.id }).returning({ id: importBatches.id }); const batchId = batch[0]?.id; if (!batchId) throw new Error("Failed to create import batch"); for (const { row, item } of resolved) { const existingRow = existing.find(candidate => candidate.stockDate === row.Date && candidate.department === row.Department && candidate.itemId === item.id); if (existingRow) throw new Error(`Approved row already exists: ${row.Date}|${row.Department}|${row.Item}`); await tx.insert(dailyStock).values({ stockDate: row.Date, department: row.Department, itemId: item.id, openingApproved: String(row.Opening), inQty: String(row.In), issued: String(row.Issued), returnQty: String(row.Return), damage: String(row.Damage), note: row.Note, autoIssued: null, manualIssued: true, createdBy: ctx.user.id }); } await writeAudit(ctx.user.id, "import", "import_batch", batchId, null, { filename: input.filename, rowCount: resolved.length }); return { batchId, rowCount: resolved.length }; }; return db.transaction ? db.transaction(apply) : apply(db);
    }),
  }),
  backup: router({
    export: protectedProcedure.query(async () => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const [itemRows, purchaseRows, stockRows, orderRows, saleRows, shopRows, recipeRows, recipeLineRows, saleShopLineRows, adjustmentRows, approvalRows, importBatchRows] = await Promise.all([db.select().from(items), db.select().from(purchases), db.select().from(dailyStock), db.select().from(orders), db.select().from(sales), db.select().from(shops), db.select().from(recipes), db.select().from(recipeLines), db.select().from(saleShopLines), db.select().from(stockAdjustments), db.select().from(approvals), db.select().from(importBatches)]); return { schemaVersion: 1, exportedAt: new Date().toISOString(), items: itemRows, purchases: purchaseRows, dailyStock: stockRows, orders: orderRows, sales: saleRows, shops: shopRows, recipes: recipeRows, recipeLines: recipeLineRows, saleShopLines: saleShopLineRows, stockAdjustments: adjustmentRows, approvals: approvalRows, importBatches: importBatchRows }; }),
    restore: adminProcedure.input(z.object({ confirm: z.literal(true), snapshot: z.unknown() })).mutation(async ({ input, ctx }) => { const migrated = migrateBackupSnapshot(input.snapshot); if (!migrated.valid) throw new Error(migrated.error); const validation = validateBackupSnapshot(migrated.snapshot); if (!validation.valid) throw new Error(validation.error); const snapshot = migrated.snapshot as any; const db = await getDb(); if (!db) throw new Error("Database unavailable"); const restore = async (tx: any) => { await tx.delete(saleShopLines); await tx.delete(recipeLines); await tx.delete(stockAdjustments); await tx.delete(sales); await tx.delete(orders); await tx.delete(dailyStock); await tx.delete(purchases); await tx.delete(recipes); await tx.delete(shops); await tx.delete(items); for (const row of snapshot.items) await tx.insert(items).values(row); for (const row of snapshot.shops) await tx.insert(shops).values(row); for (const row of snapshot.purchases) await tx.insert(purchases).values(row); for (const row of snapshot.dailyStock) await tx.insert(dailyStock).values(row); for (const row of snapshot.orders) await tx.insert(orders).values(row); for (const row of snapshot.recipes) await tx.insert(recipes).values(row); for (const row of snapshot.recipeLines) await tx.insert(recipeLines).values(row); for (const row of snapshot.sales) await tx.insert(sales).values(row); for (const row of snapshot.saleShopLines) await tx.insert(saleShopLines).values(row); for (const row of snapshot.stockAdjustments) await tx.insert(stockAdjustments).values(row); for (const row of snapshot.approvals ?? []) await tx.insert(approvals).values(row); for (const row of snapshot.importBatches ?? []) await tx.insert(importBatches).values(row); await writeAudit(ctx.user.id, "restore", "backup", null, null, { schemaVersion: snapshot.schemaVersion, collections: Object.keys(snapshot) }); return { restored: true, schemaVersion: snapshot.schemaVersion }; }; return db.transaction ? db.transaction(restore) : restore(db); }),
  }),
  costing: router({
    average: protectedProcedure.input(z.object({ itemId: z.number().int(), month: z.string().regex(/^\\d{4}-\\d{2}$/), carriedCost: numeric.nonnegative().default(0) })).query(async ({ input }) => { const db = await getDb(); if (!db) return { averageCost: input.carriedCost, purchaseQuantity: 0, purchaseValue: 0 }; const from = `${input.month}-01`; const to = `${input.month}-31`; const rows = await db.select().from(purchases).where(and(eq(purchases.itemId, input.itemId), gte(purchases.purchaseDate, from), lte(purchases.purchaseDate, to))); const averageCost = weightedAverageCost(rows.map(row => ({ quantity: Number(row.quantity), unitCost: Number(row.unitCost) })), input.carriedCost); return { averageCost, purchaseQuantity: rows.reduce((sum, row) => sum + Number(row.quantity), 0), purchaseValue: rows.reduce((sum, row) => sum + Number(row.quantity) * Number(row.unitCost), 0) }; }),
  }),
  dashboard: protectedProcedure.query(async () => {
    const db = await getDb();
    if (!db) return { items: 0, pendingApprovals: 0, purchases: 0, sales: 0 };
    const result = await db.execute(sql`SELECT (SELECT count(*)::int FROM ${items}) AS items, (SELECT count(*)::int FROM ${approvals} WHERE ${approvals.status} = 'pending') AS pending_approvals, (SELECT count(*)::int FROM ${purchases}) AS purchases, (SELECT count(*)::int FROM ${sales}) AS sales`);
    const row = result[0] as { items?: number; pending_approvals?: number; purchases?: number; sales?: number } | undefined;
    return { items: Number(row?.items ?? 0), pendingApprovals: Number(row?.pending_approvals ?? 0), purchases: Number(row?.purchases ?? 0), sales: Number(row?.sales ?? 0) };
  }),
  reports: router({
    itemLedger: protectedProcedure.input(z.object({ itemId: z.number().int(), department: z.enum(["production", "packaging"]), from: z.string(), to: z.string() }).transform(v => ({ ...v, ...normalizeDateRange(v.from, v.to) }))).query(async ({ input }) => {
      const db = await getDb();
      if (!db) return [];
      const rows = await db.select().from(dailyStock).where(and(eq(dailyStock.itemId, input.itemId), eq(dailyStock.department, input.department), lte(dailyStock.stockDate, input.to))).orderBy(asc(dailyStock.stockDate));
      const effectiveRows = rows.map(row => ({ ...row, issued: row.manualIssued ? row.issued : row.autoIssued ?? row.issued }));
      return deriveSequentialStockRows(effectiveRows).filter(entry => entry.row.stockDate >= input.from && entry.row.stockDate <= input.to).map(entry => ({ date: entry.row.stockDate, opening: entry.opening, inQty: Number(entry.row.inQty ?? 0), issued: Number(entry.row.issued ?? 0), returnQty: Number(entry.row.returnQty ?? 0), damage: Number(entry.row.damage ?? 0), used: calculateUsed({ opening: entry.opening, inQty: Number(entry.row.inQty ?? 0), issued: Number(entry.row.issued ?? 0), returnQty: Number(entry.row.returnQty ?? 0), damage: Number(entry.row.damage ?? 0) }), closing: entry.closing, note: entry.row.note ?? "" }));
    }),
    itemHistory: protectedProcedure.input(z.object({ itemId: z.number().int(), from: z.string(), to: z.string() }).transform(v => ({ ...v, ...normalizeDateRange(v.from, v.to) }))).query(async ({ input }) => {
      const db = await getDb();
      if (!db) return { averageCost: 0, events: [], totals: { quantity: 0, value: 0 } };
      const [purchaseRows, stockRows, saleRows] = await Promise.all([
        db.select().from(purchases).where(and(eq(purchases.itemId, input.itemId), gte(purchases.purchaseDate, input.from), lte(purchases.purchaseDate, input.to))),
        db.select().from(dailyStock).where(and(eq(dailyStock.itemId, input.itemId), gte(dailyStock.stockDate, input.from), lte(dailyStock.stockDate, input.to))),
        db.select().from(sales).where(and(eq(sales.itemId, input.itemId), gte(sales.saleDate, input.from), lte(sales.saleDate, input.to))),
      ]);
      const averageCost = weightedAverageCost(purchaseRows.map(row => ({ quantity: Number(row.quantity), unitCost: Number(row.unitCost) })), 0);
      const events = [
        ...purchaseRows.map(row => ({ date: row.purchaseDate, type: "Purchase", quantity: Number(row.quantity), value: Number(row.quantity) * Number(row.unitCost) })),
        ...stockRows.map(row => ({ date: row.stockDate, type: `${row.department} Closing`, quantity: Number(row.openingApproved) + Number(row.inQty) + Number(row.returnQty) - Number(row.issued), value: (Number(row.openingApproved) + Number(row.inQty) + Number(row.returnQty) - Number(row.issued)) * averageCost })),
        ...saleRows.map(row => ({ date: row.saleDate, type: "Sale", quantity: -Number(row.sell), value: -Number(row.sell) * averageCost })),
      ].sort((a, b) => a.date.localeCompare(b.date));
      return { averageCost, events, totals: { quantity: events.reduce((sum, event) => sum + event.quantity, 0), value: events.reduce((sum, event) => sum + event.value, 0) } };
    }),
    summary: protectedProcedure.input(dateRange).query(async ({ input }) => {
      const db = await getDb();
      if (!db) return { productionRows: 0, packagingRows: 0, saleRows: 0, purchaseRows: 0, movementQuantity: 0, purchaseValue: 0, salesQuantity: 0 };
      const [productionRows, packagingRows, saleRows, purchaseRows] = await Promise.all([
        db.select().from(dailyStock).where(and(eq(dailyStock.department, "production"), gte(dailyStock.stockDate, input.from), lte(dailyStock.stockDate, input.to))),
        db.select().from(dailyStock).where(and(eq(dailyStock.department, "packaging"), gte(dailyStock.stockDate, input.from), lte(dailyStock.stockDate, input.to))),
        db.select().from(sales).where(and(gte(sales.saleDate, input.from), lte(sales.saleDate, input.to))),
        db.select().from(purchases).where(and(gte(purchases.purchaseDate, input.from), lte(purchases.purchaseDate, input.to))),
      ]);
      return { productionRows: productionRows.length, packagingRows: packagingRows.length, saleRows: saleRows.length, purchaseRows: purchaseRows.length, movementQuantity: [...productionRows, ...packagingRows].reduce((sum, row) => sum + Number(row.inQty) + Number(row.issued), 0), purchaseValue: purchaseRows.reduce((sum, row) => sum + Number(row.quantity) * Number(row.unitCost), 0), salesQuantity: saleRows.reduce((sum, row) => sum + Number(row.sell), 0) };
    }),
    range: protectedProcedure.input(dateRange).query(async ({ input }) => { const db = await getDb(); if (!db) return { production: [], packaging: [], sales: [], purchases: [], inventory: [], costing: { purchaseValue: 0, averageCostByItem: [] } }; const [production, packaging, salesRows, purchasesRows, inventory] = await Promise.all([db.select().from(dailyStock).where(and(eq(dailyStock.department, "production"), gte(dailyStock.stockDate, input.from), lte(dailyStock.stockDate, input.to))), db.select().from(dailyStock).where(and(eq(dailyStock.department, "packaging"), gte(dailyStock.stockDate, input.from), lte(dailyStock.stockDate, input.to))), db.select().from(sales).where(and(gte(sales.saleDate, input.from), lte(sales.saleDate, input.to))), db.select().from(purchases).where(and(gte(purchases.purchaseDate, input.from), lte(purchases.purchaseDate, input.to))), db.select().from(dailyStock).where(and(gte(dailyStock.stockDate, input.from), lte(dailyStock.stockDate, input.to)))]); const grouped = new Map<number, { quantity: number; value: number }>(); for (const row of purchasesRows) { const current = grouped.get(row.itemId) ?? { quantity: 0, value: 0 }; current.quantity += Number(row.quantity); current.value += Number(row.quantity) * Number(row.unitCost); grouped.set(row.itemId, current); } return { production, packaging, sales: salesRows, purchases: purchasesRows, inventory, costing: { purchaseValue: purchasesRows.reduce((sum, row) => sum + Number(row.quantity) * Number(row.unitCost), 0), averageCostByItem: Array.from(grouped.entries()).map(([itemId, values]) => ({ itemId, averageCost: values.quantity ? values.value / values.quantity : 0, ...values })) } }; }),
  }),
  items: router({
    list: protectedProcedure.query(() => listItems()),
    create: protectedProcedure.input(z.object({ name: z.string().min(1), itemType: z.enum(["raw_material", "packaging_material", "finished_good", "other"]), unit: z.string().min(1), minimumStock: numeric.default(0) })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const result = await db.insert(items).values({ ...input, minimumStock: String(input.minimumStock) }).returning({ id: items.id }); const itemId = result[0]?.id; if (!itemId) throw new Error("Failed to create item"); await writeAudit(ctx.user.id, "create", "item", itemId, null, input); return { id: itemId }; }),
    update: protectedProcedure.input(z.object({ id: z.number().int(), name: z.string().min(1), itemType: z.enum(["raw_material", "packaging_material", "finished_good", "other"]), unit: z.string().min(1), minimumStock: numeric, active: z.boolean() })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const before = (await db.select().from(items).where(eq(items.id, input.id)).limit(1))[0]; await db.update(items).set({ name: input.name, itemType: input.itemType, unit: input.unit, minimumStock: String(input.minimumStock), active: input.active }).where(eq(items.id, input.id)); await writeAudit(ctx.user.id, "update", "item", input.id, before, input); return { success: true }; }),
  }),
  purchases: router({
    list: protectedProcedure.input(dateRange).query(({ input }) => listPurchases(input.from, input.to)),
    create: protectedProcedure.input(z.object({ purchaseDate: z.string(), itemId: z.number().int(), quantity: numeric.positive(), quantityUnit: z.enum(["kg", "g", "viss", "pcs"]), totalValue: numeric.nonnegative(), supplier: z.string().optional(), note: z.string().optional() })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const item = (await db.select().from(items).where(eq(items.id, input.itemId)).limit(1))[0]; if (!item) throw new Error("Item not found"); const itemBaseUnit = item.unit === "pcs" ? "pcs" : "g"; const normalized = normalizePurchase(input.quantity, input.quantityUnit, input.totalValue, itemBaseUnit); const result = await db.insert(purchases).values({ purchaseDate: input.purchaseDate, itemId: input.itemId, quantity: String(normalized.baseQuantity), unit: normalized.baseUnit, purchaseUnit: input.quantityUnit, totalValue: String(normalized.totalValue), unitCost: String(normalized.baseUnitCost), supplier: input.supplier, note: input.note, createdBy: ctx.user.id }).returning({ id: purchases.id }); const purchaseId = result[0]?.id; if (!purchaseId) throw new Error("Failed to create purchase"); await writeAudit(ctx.user.id, "create", "purchase", purchaseId, null, { ...input, ...normalized }); return { id: purchaseId, baseQuantity: normalized.baseQuantity, baseUnit: normalized.baseUnit, baseUnitCost: normalized.baseUnitCost }; }),
  }),
  stock: router({
    list: protectedProcedure.input(z.object({ department: z.enum(["production", "packaging"]), from: z.string(), to: z.string() })).query(async ({ input }) => {
      const db = await getDb();
      if (!db) return [];
      const rows = await listDailyStock(input.department, input.from, input.to);
      const [orderRows, recipeRows, lineRows, itemRows, historyRows] = await Promise.all([
        input.from === input.to
          ? db.select().from(orders).where(lte(orders.orderDate, input.to))
          : db.select().from(orders).where(and(gte(orders.orderDate, input.from), lte(orders.orderDate, input.to))),
        db.select().from(recipes).where(eq(recipes.active, true)),
        db.select().from(recipeLines),
        db.select().from(items),
        input.from === input.to
          ? db.select().from(dailyStock).where(and(eq(dailyStock.department, input.department), lte(dailyStock.stockDate, input.to))).orderBy(asc(dailyStock.stockDate))
          : Promise.resolve([] as typeof rows),
      ]);
      const isLedgerItem = (item: typeof itemRows[number]) => item.active && (input.department === "production" ? item.itemType === "raw_material" : item.itemType === "packaging_material");
      const autoFor = (stockDate: string, itemId: number) => orderRows.filter(order => order.orderDate === stockDate).reduce((sum, order) => {
        const recipe = recipeRows.filter(candidate => candidate.itemId === order.itemId && candidate.department === input.department && candidate.effectiveFrom <= stockDate).sort((a, b) => b.effectiveFrom.localeCompare(a.effectiveFrom))[0];
        const line = recipe ? lineRows.find(candidate => candidate.recipeId === recipe.id && candidate.materialItemId === itemId) : undefined;
        return sum + (line ? Number(order.quantity) * Number(line.quantityPerBatch) : 0);
      }, 0);
      const effectiveHistory = historyRows.map(row => ({ ...row, issued: row.manualIssued ? row.issued : String(autoFor(row.stockDate, row.itemId)) }));
      const derivedHistory = input.from === input.to ? deriveSequentialStockRows(effectiveHistory) : [];
      const derivedByKey = new Map(derivedHistory.map(entry => [`${entry.row.stockDate}:${entry.row.itemId}`, entry]));
      const previousClosing = (itemId: number) => [...derivedHistory].reverse().find(entry => entry.row.itemId === itemId && entry.row.stockDate < input.from)?.closing ?? 0;
      const existingByItem = new Map(rows.map(row => [row.itemId, row]));
      const baseRows = input.from === input.to ? itemRows.filter(isLedgerItem).map(item => {
        const existing = existingByItem.get(item.id);
        const derived = derivedByKey.get(`${input.from}:${item.id}`);
        if (existing) return derived ? { ...existing, openingApproved: String(derived.opening) } : existing;
        return { stockDate: input.from, department: input.department, itemId: item.id, openingApproved: String(previousClosing(item.id)), inQty: "0", issued: "0", returnQty: "0", damage: "0", note: null, autoIssued: null, manualIssued: false } as const;
      }) : rows;
      return baseRows.map(row => ({ ...row, autoIssued: String(autoFor(row.stockDate, row.itemId)) }));
    }),
    autoIssued: protectedProcedure.input(z.object({ stockDate: z.string(), department: z.enum(["production", "packaging"]), itemId: z.number().int() })).query(async ({ input }) => {
      const db = await getDb();
      if (!db) return { autoIssued: 0 };
      const [orderRows, recipeRows, lineRows] = await Promise.all([
        db.select().from(orders).where(eq(orders.orderDate, input.stockDate)),
        db.select().from(recipes).where(and(eq(recipes.active, true), lte(recipes.effectiveFrom, input.stockDate))),
        db.select().from(recipeLines),
      ]);
      const total = orderRows.reduce((sum, order) => {
        const recipe = recipeRows.filter(row => row.itemId === order.itemId && row.department === input.department).sort((a, b) => b.effectiveFrom.localeCompare(a.effectiveFrom))[0];
        const line = recipe ? lineRows.find(row => row.recipeId === recipe.id && row.materialItemId === input.itemId) : undefined;
        return sum + (line ? Number(order.quantity) * Number(line.quantityPerBatch) : 0);
      }, 0);
      return { autoIssued: total };
    }),
    save: protectedProcedure.input(z.object({ id: z.number().int().optional(), stockDate: z.string(), department: z.enum(["production", "packaging"]), itemId: z.number().int(), openingApproved: numeric, inQty: numeric, issued: numeric, returnQty: numeric, damage: numeric, note: z.string().optional(), autoIssued: numeric.optional(), manualIssued: z.boolean().default(false), openingMode: z.enum(["automatic", "manual"]).default("automatic") })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const existing = (await db.select().from(dailyStock).where(and(eq(dailyStock.stockDate, input.stockDate), eq(dailyStock.department, input.department), eq(dailyStock.itemId, input.itemId))).limit(1))[0]; const effectiveOpening = resolveOpeningQuantity(input.openingApproved, existing ? Number(existing.openingApproved) : undefined, input.openingMode as "automatic" | "manual"); const manualIssued = input.manualIssued; const effectiveIssued = resolveIssuedQuantity(input.autoIssued ?? input.issued, input.issued, manualIssued); const row = { stockDate: input.stockDate, department: input.department, itemId: input.itemId, openingApproved: String(effectiveOpening), inQty: String(input.inQty), issued: String(effectiveIssued), returnQty: String(input.returnQty), damage: String(input.damage), note: input.note, autoIssued: input.autoIssued === undefined ? null : String(input.autoIssued), manualIssued, createdBy: ctx.user.id }; if (existing) await db.update(dailyStock).set(row).where(eq(dailyStock.id, existing.id)); else await db.insert(dailyStock).values(row); const futureRows = await db.select().from(dailyStock).where(and(eq(dailyStock.department, input.department), eq(dailyStock.itemId, input.itemId), gte(dailyStock.stockDate, input.stockDate))).orderBy(dailyStock.stockDate); let previousClosing: number | null = null; for (const future of futureRows) { const opening = future.stockDate === input.stockDate ? effectiveOpening : previousClosing ?? Number(future.openingApproved); if (future.stockDate !== input.stockDate && Number(future.openingApproved) !== opening) await db.update(dailyStock).set({ openingApproved: String(opening) }).where(eq(dailyStock.id, future.id)); previousClosing = calculateClosing({ opening, inQty: future.stockDate === input.stockDate ? input.inQty : Number(future.inQty), issued: future.stockDate === input.stockDate ? effectiveIssued : Number(future.issued), returnQty: future.stockDate === input.stockDate ? input.returnQty : Number(future.returnQty), damage: Number(future.damage) }); }       return { used: calculateUsed({ opening: effectiveOpening, inQty: input.inQty, issued: effectiveIssued, returnQty: input.returnQty, damage: input.damage }), closing: calculateClosing({ opening: effectiveOpening, inQty: input.inQty, issued: effectiveIssued, returnQty: input.returnQty, damage: input.damage }) }; }),
    proposeOpening: protectedProcedure.input(z.object({ id: z.number().int(), proposedValue: numeric, reason: z.string().optional() })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const existing = (await db.select().from(dailyStock).where(eq(dailyStock.id, input.id)).limit(1))[0]; if (!existing) throw new Error("Stock row not found"); await db.update(dailyStock).set({ openingPending: String(input.proposedValue) }).where(eq(dailyStock.id, input.id)); await db.insert(approvals).values({ entityType: "opening", entityId: input.id, oldValue: existing.openingApproved, proposedValue: String(input.proposedValue), submittedBy: ctx.user.id, reason: input.reason }); return { status: "pending" as const }; }),
  }),
  adjustments: router({
    submit: protectedProcedure.input(z.object({ adjustmentDate: z.string(), department: z.enum(["production", "packaging"]), itemId: z.number().int(), proposedValue: numeric, note: z.string().optional() })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const result = await db.insert(stockAdjustments).values({ ...input, proposedValue: String(input.proposedValue), createdBy: ctx.user.id }).returning({ id: stockAdjustments.id }); const adjustmentId = result[0]?.id; if (!adjustmentId) throw new Error("Failed to create stock adjustment"); await db.insert(approvals).values({ entityType: "stock_adjustment", entityId: adjustmentId, oldValue: "0", proposedValue: String(input.proposedValue), submittedBy: ctx.user.id, reason: input.note }); return { id: adjustmentId, status: "pending" as const }; }),
  }),
  approvals: router({
    pending: adminProcedure.query(() => listPendingApprovals()),
    review: adminProcedure.input(z.object({ id: z.number().int(), decision: z.enum(["approved", "rejected"]), reason: z.string().optional() })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const approval = (await db.select().from(approvals).where(eq(approvals.id, input.id)).limit(1))[0]; if (!approval || approval.status !== "pending") throw new Error("Pending approval not found"); await db.update(approvals).set({ status: input.decision, reviewedBy: ctx.user.id, reviewedAt: new Date(), reason: input.reason ?? approval.reason }).where(eq(approvals.id, input.id)); if (approval.entityType === "opening") { const row = (await db.select().from(dailyStock).where(eq(dailyStock.id, approval.entityId)).limit(1))[0]; if (row) await db.update(dailyStock).set({ openingApproved: input.decision === "approved" ? approval.proposedValue : row.openingApproved, openingPending: null }).where(eq(dailyStock.id, row.id)); } if (approval.entityType === "stock_adjustment" && input.decision === "approved") { const adjustment = (await db.select().from(stockAdjustments).where(eq(stockAdjustments.id, approval.entityId)).limit(1))[0]; if (adjustment) { const row = (await db.select().from(dailyStock).where(and(eq(dailyStock.stockDate, adjustment.adjustmentDate), eq(dailyStock.department, adjustment.department), eq(dailyStock.itemId, adjustment.itemId))).limit(1))[0]; if (row) await db.update(dailyStock).set({ openingApproved: approval.proposedValue }).where(eq(dailyStock.id, row.id)); } } await writeAudit(ctx.user.id, input.decision, approval.entityType, approval.entityId, approval, { ...approval, status: input.decision }); return { success: true }; }),
  }),
  orders: router({
    list: protectedProcedure.input(dateRange).query(async ({ input }) => { const db = await getDb(); if (!db) return []; return db.select().from(orders).where(and(gte(orders.orderDate, input.from), lte(orders.orderDate, input.to))).orderBy(desc(orders.orderDate)); }),
    create: protectedProcedure.input(z.object({ orderDate: z.string(), itemId: z.number().int(), quantity: numeric.positive(), note: z.string().optional() })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const item = (await db.select({ id: items.id, active: items.active, itemType: items.itemType }).from(items).where(eq(items.id, input.itemId)).limit(1))[0]; if (!item || !item.active || item.itemType !== "finished_good") throw new Error("Orders can only be created for active Sale items."); const result = await db.insert(orders).values({ ...input, quantity: String(input.quantity), createdBy: ctx.user.id }).returning({ id: orders.id }); return { id: result[0]?.id }; }),
  }),
  recipes: router({
    list: protectedProcedure.query(async () => { const db = await getDb(); if (!db) return []; return db.select().from(recipes).orderBy(desc(recipes.effectiveFrom)); }),
    create: protectedProcedure.input(z.object({ itemId: z.number().int(), department: z.enum(["production", "packaging"]).default("production"), effectiveFrom: z.string(), note: z.string().optional(), lines: z.array(z.object({ materialItemId: z.number().int(), quantityPerBatch: numeric.positive(), unit: z.string().min(1) })) })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const result = await db.insert(recipes).values({ itemId: input.itemId, department: input.department, effectiveFrom: input.effectiveFrom, note: input.note, createdBy: ctx.user.id }).returning({ id: recipes.id }); const recipeId = result[0]?.id; if (!recipeId) throw new Error("Failed to create recipe"); if (input.lines.length) await db.insert(recipeLines).values(input.lines.map(line => ({ recipeId, materialItemId: line.materialItemId, quantityPerBatch: String(line.quantityPerBatch), unit: line.unit }))); return { id: recipeId }; }),
    detail: protectedProcedure.input(z.object({ id: z.number().int() })).query(async ({ input }) => { const db = await getDb(); if (!db) return []; return db.select().from(recipeLines).where(eq(recipeLines.recipeId, input.id)); }),
    update: protectedProcedure.input(z.object({ id: z.number().int(), department: z.enum(["production", "packaging"]).optional(), effectiveFrom: z.string(), note: z.string().optional(), lines: z.array(z.object({ materialItemId: z.number().int(), quantityPerBatch: numeric.positive(), unit: z.string().min(1) })) })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(recipes).set({ ...(input.department ? { department: input.department } : {}), effectiveFrom: input.effectiveFrom, note: input.note }).where(eq(recipes.id, input.id)); await db.delete(recipeLines).where(eq(recipeLines.recipeId, input.id)); if (input.lines.length) await db.insert(recipeLines).values(input.lines.map(line => ({ recipeId: input.id, materialItemId: line.materialItemId, quantityPerBatch: String(line.quantityPerBatch), unit: line.unit }))); return { success: true }; }),
    setActive: protectedProcedure.input(z.object({ id: z.number().int(), active: z.boolean() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const recipe = (await db.select().from(recipes).where(eq(recipes.id, input.id)).limit(1))[0]; if (!recipe) throw new Error("Recipe not found"); if (input.active) await db.update(recipes).set({ active: false }).where(and(eq(recipes.itemId, recipe.itemId), eq(recipes.department, recipe.department))); await db.update(recipes).set({ active: input.active }).where(eq(recipes.id, input.id)); return { success: true }; }),
  }),
  shops: router({ list: protectedProcedure.query(() => listShops()), create: protectedProcedure.input(z.object({ name: z.string().min(1) })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const result = await db.insert(shops).values({ name: input.name }).returning({ id: shops.id }); return { id: result[0]?.id }; }) }),
  sales: router({
    list: protectedProcedure.input(dateRange).query(({ input }) => listSales(input.from, input.to)),
    detail: protectedProcedure.input(z.object({ saleId: z.number().int() })).query(async ({ input }) => { const db = await getDb(); if (!db) return []; return db.select().from(saleShopLines).where(eq(saleShopLines.saleId, input.saleId)); }),
    save: protectedProcedure.input(z.object({ id: z.number().int().optional(), saleDate: z.string(), itemId: z.number().int(), opening: numeric, produce: numeric, shopLines: z.array(z.object({ shopId: z.number().int(), quantity: numeric.nonnegative() })), note: z.string().optional() })).mutation(async ({ input, ctx }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const sell = sumShopQuantities(input.shopLines); const existing = input.id ? (await db.select().from(sales).where(eq(sales.id, input.id)).limit(1))[0] : (await db.select().from(sales).where(and(eq(sales.saleDate, input.saleDate), eq(sales.itemId, input.itemId))).limit(1))[0]; let saleId = input.id; if (existing) await db.update(sales).set({ opening: String(input.opening), produce: String(input.produce), sell: String(sell), note: input.note }).where(eq(sales.id, existing.id)); else { const result = await db.insert(sales).values({ saleDate: input.saleDate, itemId: input.itemId, opening: String(input.opening), produce: String(input.produce), sell: String(sell), note: input.note, createdBy: ctx.user.id }).returning({ id: sales.id }); saleId = result[0]?.id; } if (saleId) { await db.delete(saleShopLines).where(eq(saleShopLines.saleId, saleId)); if (input.shopLines.length) await db.insert(saleShopLines).values(input.shopLines.map(line => ({ saleId: saleId!, shopId: line.shopId, quantity: String(line.quantity) }))); } return { sell, closing: input.opening + input.produce - sell }; }),
  }),
});

export type AppRouter = typeof appRouter;
